service: whatevar
region: eu-3
package:
  include:
   - node_modules/**
provider:
    name: aws
    runtime: nodejs8.10
functions:
  send:
    handler: handler.deviceData
    events:
      - http:
          path: api/device/businesses/{lat}/{long}
          method: get
          parameters:
            paths:
              lat: true
              long: true